spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instachatdb
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: FGW390@#7&Ounjkebu!#%%GHOPQasx&Q
  expiration: 3600000
