spring:
  datasource:
    url: ${JDBC_DATABASE_URL:}
frontend:
  url: ${FRONTEND_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: FGW390@#7&Ounjkebu!#%%GHOPQasx&Q
  expiration: 3600000